# Generated by Django 3.2.12 on 2022-03-29 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='idade',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Idade do Funcionário'),
        ),
    ]
